version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./code:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  php:
    build: ./php
    volumes:
      - ./code:/code
  maria:
    image: mariadb:latest
    environment:
     - MYSQL_ROOT_PASSWORD=nope
     - MYSQL_DATABASE=db